# Generated by Django 4.1.5 on 2023-02-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_picz_memebers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=700)),
                ('picz', models.ImageField(blank=True, null=True, upload_to='aboutpicz')),
                ('about_creators', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='clearancepicz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clearpicz', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz1', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz2', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz3', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz4', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz5', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz6', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz7', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('clearpicz8', models.ImageField(blank=True, null=True, upload_to='clearancepicz')),
                ('name', models.TextField(max_length=3000)),
                ('full_description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='halls/%Y/%m/%d')),
                ('short_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'hall',
                'verbose_name_plural': 'halls',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='home_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=300)),
                ('picz', models.ImageField(blank=True, null=True, upload_to='homeshit')),
                ('datez', models.DateTimeField(auto_now_add=True)),
                ('header', models.TextField(max_length=800)),
                ('story', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='how_picz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=4000)),
                ('picz', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz1', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz2', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz3', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz4', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz5', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz6', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz7', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz8', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz9', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz10', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('picz11', models.ImageField(blank=True, null=True, upload_to='howto')),
                ('description', models.TextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='kgaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('concept', models.CharField(max_length=1000)),
                ('picz', models.ImageField(upload_to='greatness_art')),
                ('price_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reg_ex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('body', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='regista_pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=3000)),
                ('description', models.TextField(max_length=3000)),
                ('picz', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz1', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz2', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz3', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz4', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz5', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz6', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz7', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
                ('picz8', models.ImageField(blank=True, null=True, upload_to='regista_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='workz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_title', models.CharField(max_length=300)),
                ('foot_body', models.CharField(max_length=5000)),
                ('picz1', models.ImageField(blank=True, null=True, upload_to='work')),
                ('picz2', models.ImageField(blank=True, null=True, upload_to='work')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('name2', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='halls/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('full_description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_halls', to='halls.hall')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
