# Generated by Django 3.0.5 on 2023-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_auto_20230225_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancepicz',
            name='name',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='how_picz',
            name='name',
            field=models.TextField(max_length=1000),
        ),
    ]
