# Generated by Django 4.1.5 on 2023-02-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clearanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reg_no', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
                ('school', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='examForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg_no', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=7000)),
                ('school', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='projectForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regno', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=2000)),
                ('project_topic', models.CharField(max_length=2000)),
                ('school', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='registrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('app_no', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=30)),
                ('school', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='regular_assessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reg_no', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('department', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('school', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='clearance_form',
        ),
        migrations.DeleteModel(
            name='exam_form',
        ),
        migrations.DeleteModel(
            name='project_form',
        ),
        migrations.DeleteModel(
            name='registration_form',
        ),
        migrations.DeleteModel(
            name='regular_assessment_tasks',
        ),
    ]
