# Generated by Django 3.0.5 on 2023-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imt', '0003_auto_20230225_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contact_info',
            name='address2',
        ),
        migrations.AddField(
            model_name='contact_info',
            name='add1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contact_info',
            name='add2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
