# Generated by Django 3.0.5 on 2023-03-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imt', '0004_auto_20230304_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_info',
        ),
    ]
